version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

  flask-app:
    container_name: flask-app
    image: trio-flask-app:latest
    build: ./flask-app
    environment:
      MYSQL_ROOT_PASSWORD: "$(DBPASSWORD)"

  mysql:
    container_name: mysql
    image: trio-db:latest
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: "$(DBPASSWORD)"
    volumes:
      - type: volume
        source: new-mysqlvolume
        target: /var/lib/mysql

volumes:
  new-mysqlvolume:
