version: '3.8' #mandatory

services: #containers
  web:
    image: nginx:latest
    #build: . or ./ (if we don't have it locally.)
    ports:
      - "80:80"

  db:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
